name: share_buy_list
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  artemis: ^7.1.1-beta.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^1.2.0
  google_mobile_ads: ^1.2.0
  graphql_flutter: ^5.0.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.1.5
  pedantic_mono: ^1.17.0
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  tab_indicator_styler: ^2.0.0
  webview_flutter: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true