name: Deploy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.CRYPT_PUB_KEY }}
      - name: set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: install flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze

  build_android:
    name: build android
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.CRYPT_PUB_KEY }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: install flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.2'
          channel: 'stable'

      - name: flutter dependencies install
        run: flutter pub get

      - name: build apk
        run: |
          flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy_android:
    name: deploy android
    needs: [build_android]
    runs-on: ubuntu-latest
    steps:

      - name: set up repository
        uses: actions/checkout@v2
      - name: unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.CRYPT_PUB_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: android

      # Deploy to Firebase
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: android/app-release.apk
          groups: primary_testers

